---
name: Build and Push Image

on:
  push:
    tags:
      - "*"

    branches-ignore:
      - "dependabot/**"

    paths-ignore:
      - "**.md"
      - ".vscode/**"
      - ".github/**"

concurrency: build-${{ github.ref }}

jobs:
  build:
    uses: ditkrg/build-image-workflow/.github/workflows/workflow.yaml@v1
    with:
      image: common/backend-for-frontends
    secrets:
      username: ${{ secrets.HARBOR_USER }}
      password: ${{ secrets.HARBOR_TOKEN }}
