name: Build and Push Images

on:
  push:
    branches:
      - "*"

env:
  IMAGE: reg.dev.krd/common/backend-for-frontends

concurrency: build-${{ github.ref }}

jobs:
  build-push:
    runs-on: [self-hosted, ubuntu-focal]
    steps:
      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DIT Registry
        uses: docker/login-action@v1
        with:
          registry: reg.dev.krd
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE }}:${{ env.BRANCH_NAME }}
          cache-to: type=inline
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:${{ env.BRANCH_NAME }}
