name: Build and Push Images

on:
  push:
    branches:
      - "*"

concurrency: build-${{ github.ref }}

jobs:
  build:
    uses: ditkrg/common-github-workflows/.github/workflows/build-push-image.yaml@main
    with:
      tags: |-
        reg.dev.krd/common/backend-for-frontends:${{ github.ref_name }}
        reg.dev.krd/common/backend-for-frontends:${{ github.ref_name }}-${{ github.sha }}
      cache-from: type=registry,ref=reg.dev.krd/common/backend-for-frontends:${{ github.ref_name }}
    secrets:
      username: ${{ secrets.HARBOR_USER }}
      password: ${{ secrets.HARBOR_TOKEN }}
