---
name: CI

on:
  push:
    branches:
      - "dependabot/**"

  pull_request:
    branches: [main, dev]

jobs:
  run-tests:
    name: Run Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn build
