name: Tag Release Image

on:
  release:
    types:
      - published
      - prereleased
env:
  IMAGE: reg.dev.krd/common/backend-for-frontends

jobs:
  deploy:
    runs-on: self-hosted # run on self-hosted runner
    steps:
      - name: Get tag name
        shell: bash
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to DIT Registry
        uses: docker/login-action@v1
        with:
          registry: reg.dev.krd
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE }}:${{ github.sha }}
          cache-to: type=inline
          tags: |
            ${{ env.IMAGE }}:${{ env.TAG_NAME }}
