name: Tag Release Image

on:
  release:
    types:
      - published

concurrency: release-${{ github.ref }}

jobs:
  build:
    uses: ditkrg/common-github-workflows/.github/workflows/build-push-image.yaml@main
    with:
      tags: reg.dev.krd/common/backend-for-frontends:${{ github.ref_name }}
      cache-from: type=registry,ref=reg.dev.krd/common/backend-for-frontends:${{ github.ref_name }}
    secrets:
      username: ${{ secrets.HARBOR_USER }}
      password: ${{ secrets.HARBOR_TOKEN }}
